site_name: VSTS Data Bulk Editor
pages:
- Home: index.md
- Usage:
  - Usage: usage/usage.md
  - Command Line: usage/command-line.md
  - NuGet Library: usage/nuget-library.md
- Configuration: configuration.md
theme: readthedocs
