optionsClassName: TfsTeamSettingsProcessorOptions
optionsClassFullName: MigrationTools.Processors.TfsTeamSettingsProcessorOptions
configurationSamples:
- name: defaults
  order: 2
  description: 
  code: There are no defaults! Check the sample for options!
  sampleFor: MigrationTools.Processors.TfsTeamSettingsProcessorOptions
- name: sample
  order: 1
  description: 
  code: There is no sample, but you can check the classic below for a general feel.
  sampleFor: MigrationTools.Processors.TfsTeamSettingsProcessorOptions
- name: classic
  order: 3
  description: 
  code: >-
    {
      "$type": "TfsTeamSettingsProcessorOptions",
      "Enabled": false,
      "MigrateTeamSettings": false,
      "UpdateTeamSettings": false,
      "PrefixProjectToNodes": false,
      "MigrateTeamCapacities": false,
      "Teams": null,
      "UseUserMapping": false,
      "SourceName": null,
      "TargetName": null
    }
  sampleFor: MigrationTools.Processors.TfsTeamSettingsProcessorOptions
description: Native TFS Processor, does not work with any other Endpoints.
className: TfsTeamSettingsProcessor
typeName: Processors
architecture: 
options:
- parameterName: Enabled
  type: Boolean
  description: If set to `true` then the processor will run. Set to `false` and the processor will not run.
  defaultValue: missing XML code comments
- parameterName: MigrateTeamCapacities
  type: Boolean
  description: 'Migrate original team member capacities after their creation on the target team project. Note: It will only migrate team member capacity if the team member with same display name exists on the target collection otherwise it will be ignored.'
  defaultValue: false
- parameterName: MigrateTeamSettings
  type: Boolean
  description: Migrate original team settings after their creation on target team project
  defaultValue: false
- parameterName: PrefixProjectToNodes
  type: Boolean
  description: Prefix your iterations and areas with the project name. If you have enabled this in `NodeStructuresMigrationConfig` you must do it here too.
  defaultValue: false
- parameterName: SourceName
  type: String
  description: missing XML code comments
  defaultValue: missing XML code comments
- parameterName: TargetName
  type: String
  description: missing XML code comments
  defaultValue: missing XML code comments
- parameterName: Teams
  type: List
  description: List of Teams to process. If this is `null` then all teams will be processed.
  defaultValue: missing XML code comments
- parameterName: UpdateTeamSettings
  type: Boolean
  description: Reset the target team settings to match the source if the team exists
  defaultValue: false
- parameterName: UseUserMapping
  type: Boolean
  description: Use user mapping file from TfsTeamSettingsTool when matching users when migrating capacities. By default, users in source are matched in target users by current display name. When this is set to `true`, users are matched also by mapped name from user mapping file.
  defaultValue: missing XML code comments
status: Beta
processingTarget: Teams
classFile: src/MigrationTools.Clients.TfsObjectModel/Processors/TfsTeamSettingsProcessor.cs
optionsClassFile: src/MigrationTools.Clients.TfsObjectModel/Processors/TfsTeamSettingsProcessorOptions.cs
