name: Azure Static Web App PR Cleanup

on:
  pull_request:
    types: [closed]

jobs:
  pr_cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.NKDAGILITY_BOT_APP_ID }}
          private-key: ${{ secrets.NKDAGILITY_BOT_CLIENTSECRET }}
      - name: Clean up pull request environment
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: 'close'
          app_location: ''
          skip_app_build: true
          skip_api_build: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
